feat: scrape single URL action
apify/apify-zapier-integration pull request #44
Opened 2023-10-09 13:17 UTC by drobnikj

2023-10-10 09:04 UTC, fnesveda requested changes
Looks good, just one problem with the example data

2023-10-10 09:04 UTC, fnesveda commented on src/consts.js
> +    detailsPageUrl: 'https://console.apify.com/actors/$actId/runs/HG7ML7M8z78YcAPEB',
Should the `$actId` be here?

2023-10-10 10:37 UTC, TheoVasilis requested changes

2023-10-10 10:37 UTC, TheoVasilis commented on src/creates/scrape_single_url.js
> +                    + 'Behind the scenes, it utilizes the [Website Content Crawler](https://apify.com/apify/website-content-crawler). '
```suggestion
                    + 'Behind the scenes, it utilizes [Website Content Crawler](https://apify.com/apify/website-content-crawler). '
```

2023-10-10 10:37 UTC, TheoVasilis commented on src/creates/scrape_single_url.js
> +                    + 'You can choose to run either the [Website Content Crawler](https://apify.com/apify/website-content-crawler) or '
```suggestion
                    + 'You can choose to run either [Website Content Crawler](https://apify.com/apify/website-content-crawler) or '
```

2023-10-10 10:37 UTC, TheoVasilis commented on src/creates/scrape_single_url.js
> +                    + 'the [Web Scraper](https://apify.com/apify/web-scraper), '
```suggestion
                    + '[Web Scraper](https://apify.com/apify/web-scraper), '
```

2023-10-10 10:37 UTC, TheoVasilis commented on src/creates/scrape_single_url.js
> +                    + 'Try this if you encounter bot protection while scraping. \n'
```suggestion
                    + 'Try this if you encounter anti-bot protections while scraping. \n'
```

2023-10-10 10:37 UTC, TheoVasilis commented on src/creates/scrape_single_url.js
> +                        + 'Very reliable, best in avoiding blocking, but might be slow',
```suggestion
                        + 'Very reliable. Great for avoiding blocking, but it might be slow',
```

2023-10-10 14:13 UTC, TheoVasilis approved these changes

2023-10-10 14:46 UTC, fnesveda approved these changes

2023-10-11 09:39 UTC, jirimoravcik approved these changes

2023-10-11 09:39 UTC, jirimoravcik commented on src/creates/scrape_single_url.js
> +    const timeoutSecs = 30;
tests have timeouts of 60 and 65 secs, but only 30 here 😅

2023-10-12 08:44 UTC, merged